<?php

namespace App\Backend\Modules\Core\Inventory;

class InventoryModule
{
    public const MODULE_KEY = 'inventory';

    public static function features(): array
    {
        return [
            'unlimited_products',
            'categories',
            'brands',
            'units',
            'product_images',
            'barcode_generation',
            'batch_numbers',
            'expiry_dates',
            'serial_numbers',
            'stock_transfers',
            'stock_adjustments',
            'reorder_levels',
            'purchase_orders',
            'supplier_orders',
            'warehouse_management',
            'multiple_warehouses',
            'inventory_valuation',
            'inventory_history',
            'damaged_stock',
            'lost_stock',
            'cycle_counts',
        ];
    }

    public static function routes(): array
    {
        return [
            'GET /api/modules/inventory/unlimited_products' => [Controllers\UnlimitedProductsController::class, 'index'],
            'POST /api/modules/inventory/unlimited_products' => [Controllers\UnlimitedProductsController::class, 'store'],
            'GET /api/modules/inventory/unlimited_products/{id}' => [Controllers\UnlimitedProductsController::class, 'show'],
            'PUT /api/modules/inventory/unlimited_products/{id}' => [Controllers\UnlimitedProductsController::class, 'update'],
            'DELETE /api/modules/inventory/unlimited_products/{id}' => [Controllers\UnlimitedProductsController::class, 'destroy'],
            'GET /api/modules/inventory/categories' => [Controllers\CategoriesController::class, 'index'],
            'POST /api/modules/inventory/categories' => [Controllers\CategoriesController::class, 'store'],
            'GET /api/modules/inventory/categories/{id}' => [Controllers\CategoriesController::class, 'show'],
            'PUT /api/modules/inventory/categories/{id}' => [Controllers\CategoriesController::class, 'update'],
            'DELETE /api/modules/inventory/categories/{id}' => [Controllers\CategoriesController::class, 'destroy'],
            'GET /api/modules/inventory/brands' => [Controllers\BrandsController::class, 'index'],
            'POST /api/modules/inventory/brands' => [Controllers\BrandsController::class, 'store'],
            'GET /api/modules/inventory/brands/{id}' => [Controllers\BrandsController::class, 'show'],
            'PUT /api/modules/inventory/brands/{id}' => [Controllers\BrandsController::class, 'update'],
            'DELETE /api/modules/inventory/brands/{id}' => [Controllers\BrandsController::class, 'destroy'],
            'GET /api/modules/inventory/units' => [Controllers\UnitsController::class, 'index'],
            'POST /api/modules/inventory/units' => [Controllers\UnitsController::class, 'store'],
            'GET /api/modules/inventory/units/{id}' => [Controllers\UnitsController::class, 'show'],
            'PUT /api/modules/inventory/units/{id}' => [Controllers\UnitsController::class, 'update'],
            'DELETE /api/modules/inventory/units/{id}' => [Controllers\UnitsController::class, 'destroy'],
            'GET /api/modules/inventory/product_images' => [Controllers\ProductImagesController::class, 'index'],
            'POST /api/modules/inventory/product_images' => [Controllers\ProductImagesController::class, 'store'],
            'GET /api/modules/inventory/product_images/{id}' => [Controllers\ProductImagesController::class, 'show'],
            'PUT /api/modules/inventory/product_images/{id}' => [Controllers\ProductImagesController::class, 'update'],
            'DELETE /api/modules/inventory/product_images/{id}' => [Controllers\ProductImagesController::class, 'destroy'],
            'GET /api/modules/inventory/barcode_generation' => [Controllers\BarcodeGenerationController::class, 'index'],
            'POST /api/modules/inventory/barcode_generation' => [Controllers\BarcodeGenerationController::class, 'store'],
            'GET /api/modules/inventory/barcode_generation/{id}' => [Controllers\BarcodeGenerationController::class, 'show'],
            'PUT /api/modules/inventory/barcode_generation/{id}' => [Controllers\BarcodeGenerationController::class, 'update'],
            'DELETE /api/modules/inventory/barcode_generation/{id}' => [Controllers\BarcodeGenerationController::class, 'destroy'],
            'GET /api/modules/inventory/batch_numbers' => [Controllers\BatchNumbersController::class, 'index'],
            'POST /api/modules/inventory/batch_numbers' => [Controllers\BatchNumbersController::class, 'store'],
            'GET /api/modules/inventory/batch_numbers/{id}' => [Controllers\BatchNumbersController::class, 'show'],
            'PUT /api/modules/inventory/batch_numbers/{id}' => [Controllers\BatchNumbersController::class, 'update'],
            'DELETE /api/modules/inventory/batch_numbers/{id}' => [Controllers\BatchNumbersController::class, 'destroy'],
            'GET /api/modules/inventory/expiry_dates' => [Controllers\ExpiryDatesController::class, 'index'],
            'POST /api/modules/inventory/expiry_dates' => [Controllers\ExpiryDatesController::class, 'store'],
            'GET /api/modules/inventory/expiry_dates/{id}' => [Controllers\ExpiryDatesController::class, 'show'],
            'PUT /api/modules/inventory/expiry_dates/{id}' => [Controllers\ExpiryDatesController::class, 'update'],
            'DELETE /api/modules/inventory/expiry_dates/{id}' => [Controllers\ExpiryDatesController::class, 'destroy'],
            'GET /api/modules/inventory/serial_numbers' => [Controllers\SerialNumbersController::class, 'index'],
            'POST /api/modules/inventory/serial_numbers' => [Controllers\SerialNumbersController::class, 'store'],
            'GET /api/modules/inventory/serial_numbers/{id}' => [Controllers\SerialNumbersController::class, 'show'],
            'PUT /api/modules/inventory/serial_numbers/{id}' => [Controllers\SerialNumbersController::class, 'update'],
            'DELETE /api/modules/inventory/serial_numbers/{id}' => [Controllers\SerialNumbersController::class, 'destroy'],
            'GET /api/modules/inventory/stock_transfers' => [Controllers\StockTransfersController::class, 'index'],
            'POST /api/modules/inventory/stock_transfers' => [Controllers\StockTransfersController::class, 'store'],
            'GET /api/modules/inventory/stock_transfers/{id}' => [Controllers\StockTransfersController::class, 'show'],
            'PUT /api/modules/inventory/stock_transfers/{id}' => [Controllers\StockTransfersController::class, 'update'],
            'DELETE /api/modules/inventory/stock_transfers/{id}' => [Controllers\StockTransfersController::class, 'destroy'],
            'GET /api/modules/inventory/stock_adjustments' => [Controllers\StockAdjustmentsController::class, 'index'],
            'POST /api/modules/inventory/stock_adjustments' => [Controllers\StockAdjustmentsController::class, 'store'],
            'GET /api/modules/inventory/stock_adjustments/{id}' => [Controllers\StockAdjustmentsController::class, 'show'],
            'PUT /api/modules/inventory/stock_adjustments/{id}' => [Controllers\StockAdjustmentsController::class, 'update'],
            'DELETE /api/modules/inventory/stock_adjustments/{id}' => [Controllers\StockAdjustmentsController::class, 'destroy'],
            'GET /api/modules/inventory/reorder_levels' => [Controllers\ReorderLevelsController::class, 'index'],
            'POST /api/modules/inventory/reorder_levels' => [Controllers\ReorderLevelsController::class, 'store'],
            'GET /api/modules/inventory/reorder_levels/{id}' => [Controllers\ReorderLevelsController::class, 'show'],
            'PUT /api/modules/inventory/reorder_levels/{id}' => [Controllers\ReorderLevelsController::class, 'update'],
            'DELETE /api/modules/inventory/reorder_levels/{id}' => [Controllers\ReorderLevelsController::class, 'destroy'],
            'GET /api/modules/inventory/purchase_orders' => [Controllers\PurchaseOrdersController::class, 'index'],
            'POST /api/modules/inventory/purchase_orders' => [Controllers\PurchaseOrdersController::class, 'store'],
            'GET /api/modules/inventory/purchase_orders/{id}' => [Controllers\PurchaseOrdersController::class, 'show'],
            'PUT /api/modules/inventory/purchase_orders/{id}' => [Controllers\PurchaseOrdersController::class, 'update'],
            'DELETE /api/modules/inventory/purchase_orders/{id}' => [Controllers\PurchaseOrdersController::class, 'destroy'],
            'GET /api/modules/inventory/supplier_orders' => [Controllers\SupplierOrdersController::class, 'index'],
            'POST /api/modules/inventory/supplier_orders' => [Controllers\SupplierOrdersController::class, 'store'],
            'GET /api/modules/inventory/supplier_orders/{id}' => [Controllers\SupplierOrdersController::class, 'show'],
            'PUT /api/modules/inventory/supplier_orders/{id}' => [Controllers\SupplierOrdersController::class, 'update'],
            'DELETE /api/modules/inventory/supplier_orders/{id}' => [Controllers\SupplierOrdersController::class, 'destroy'],
            'GET /api/modules/inventory/warehouse_management' => [Controllers\WarehouseManagementController::class, 'index'],
            'POST /api/modules/inventory/warehouse_management' => [Controllers\WarehouseManagementController::class, 'store'],
            'GET /api/modules/inventory/warehouse_management/{id}' => [Controllers\WarehouseManagementController::class, 'show'],
            'PUT /api/modules/inventory/warehouse_management/{id}' => [Controllers\WarehouseManagementController::class, 'update'],
            'DELETE /api/modules/inventory/warehouse_management/{id}' => [Controllers\WarehouseManagementController::class, 'destroy'],
            'GET /api/modules/inventory/multiple_warehouses' => [Controllers\MultipleWarehousesController::class, 'index'],
            'POST /api/modules/inventory/multiple_warehouses' => [Controllers\MultipleWarehousesController::class, 'store'],
            'GET /api/modules/inventory/multiple_warehouses/{id}' => [Controllers\MultipleWarehousesController::class, 'show'],
            'PUT /api/modules/inventory/multiple_warehouses/{id}' => [Controllers\MultipleWarehousesController::class, 'update'],
            'DELETE /api/modules/inventory/multiple_warehouses/{id}' => [Controllers\MultipleWarehousesController::class, 'destroy'],
            'GET /api/modules/inventory/inventory_valuation' => [Controllers\InventoryValuationController::class, 'index'],
            'POST /api/modules/inventory/inventory_valuation' => [Controllers\InventoryValuationController::class, 'store'],
            'GET /api/modules/inventory/inventory_valuation/{id}' => [Controllers\InventoryValuationController::class, 'show'],
            'PUT /api/modules/inventory/inventory_valuation/{id}' => [Controllers\InventoryValuationController::class, 'update'],
            'DELETE /api/modules/inventory/inventory_valuation/{id}' => [Controllers\InventoryValuationController::class, 'destroy'],
            'GET /api/modules/inventory/inventory_history' => [Controllers\InventoryHistoryController::class, 'index'],
            'POST /api/modules/inventory/inventory_history' => [Controllers\InventoryHistoryController::class, 'store'],
            'GET /api/modules/inventory/inventory_history/{id}' => [Controllers\InventoryHistoryController::class, 'show'],
            'PUT /api/modules/inventory/inventory_history/{id}' => [Controllers\InventoryHistoryController::class, 'update'],
            'DELETE /api/modules/inventory/inventory_history/{id}' => [Controllers\InventoryHistoryController::class, 'destroy'],
            'GET /api/modules/inventory/damaged_stock' => [Controllers\DamagedStockController::class, 'index'],
            'POST /api/modules/inventory/damaged_stock' => [Controllers\DamagedStockController::class, 'store'],
            'GET /api/modules/inventory/damaged_stock/{id}' => [Controllers\DamagedStockController::class, 'show'],
            'PUT /api/modules/inventory/damaged_stock/{id}' => [Controllers\DamagedStockController::class, 'update'],
            'DELETE /api/modules/inventory/damaged_stock/{id}' => [Controllers\DamagedStockController::class, 'destroy'],
            'GET /api/modules/inventory/lost_stock' => [Controllers\LostStockController::class, 'index'],
            'POST /api/modules/inventory/lost_stock' => [Controllers\LostStockController::class, 'store'],
            'GET /api/modules/inventory/lost_stock/{id}' => [Controllers\LostStockController::class, 'show'],
            'PUT /api/modules/inventory/lost_stock/{id}' => [Controllers\LostStockController::class, 'update'],
            'DELETE /api/modules/inventory/lost_stock/{id}' => [Controllers\LostStockController::class, 'destroy'],
            'GET /api/modules/inventory/cycle_counts' => [Controllers\CycleCountsController::class, 'index'],
            'POST /api/modules/inventory/cycle_counts' => [Controllers\CycleCountsController::class, 'store'],
            'GET /api/modules/inventory/cycle_counts/{id}' => [Controllers\CycleCountsController::class, 'show'],
            'PUT /api/modules/inventory/cycle_counts/{id}' => [Controllers\CycleCountsController::class, 'update'],
            'DELETE /api/modules/inventory/cycle_counts/{id}' => [Controllers\CycleCountsController::class, 'destroy'],
        ];
    }
}
