<?php

namespace App\Backend\Modules\Industry\RestaurantHotels\Restaurant;

class RestaurantSubmodule
{
    public const MODULE_KEY = 'restaurant_hotels';
    public const SUBMODULE_KEY = 'restaurant';

    public static function features(): array
    {
        return [            'tables',
            'table_management',
            'table_reservations',
            'qr_ordering',
            'table_transfer',
            'merge_tables',
            'split_bills',
            'kitchen_display_system',
            'kitchen_printing',
            'cooking_status',
            'food_preparation_timers',
            'recipe_management',
            'ingredients_tracking',
            'waiter_assignment',
            'waiter_commissions',
            'order_tracking',
            'menu_categories',
            'combos',
            'meal_customization',
            'add_ons',
            'happy_hour_pricing',
            'delivery_riders',
            'delivery_tracking',
            'online_orders',
            'pickup_orders',
        ];
    }

    public static function routes(): array
    {
        return [            'GET /api/modules/restaurant_hotels/restaurant/tables' => [Controllers\TablesController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/tables' => [Controllers\TablesController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/tables/{id}' => [Controllers\TablesController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/tables/{id}' => [Controllers\TablesController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/tables/{id}' => [Controllers\TablesController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/table_management' => [Controllers\TableManagementController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/table_management' => [Controllers\TableManagementController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/table_management/{id}' => [Controllers\TableManagementController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/table_management/{id}' => [Controllers\TableManagementController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/table_management/{id}' => [Controllers\TableManagementController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/table_reservations' => [Controllers\TableReservationsController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/table_reservations' => [Controllers\TableReservationsController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/table_reservations/{id}' => [Controllers\TableReservationsController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/table_reservations/{id}' => [Controllers\TableReservationsController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/table_reservations/{id}' => [Controllers\TableReservationsController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/qr_ordering' => [Controllers\QrOrderingController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/qr_ordering' => [Controllers\QrOrderingController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/qr_ordering/{id}' => [Controllers\QrOrderingController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/qr_ordering/{id}' => [Controllers\QrOrderingController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/qr_ordering/{id}' => [Controllers\QrOrderingController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/table_transfer' => [Controllers\TableTransferController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/table_transfer' => [Controllers\TableTransferController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/table_transfer/{id}' => [Controllers\TableTransferController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/table_transfer/{id}' => [Controllers\TableTransferController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/table_transfer/{id}' => [Controllers\TableTransferController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/merge_tables' => [Controllers\MergeTablesController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/merge_tables' => [Controllers\MergeTablesController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/merge_tables/{id}' => [Controllers\MergeTablesController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/merge_tables/{id}' => [Controllers\MergeTablesController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/merge_tables/{id}' => [Controllers\MergeTablesController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/split_bills' => [Controllers\SplitBillsController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/split_bills' => [Controllers\SplitBillsController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/split_bills/{id}' => [Controllers\SplitBillsController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/split_bills/{id}' => [Controllers\SplitBillsController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/split_bills/{id}' => [Controllers\SplitBillsController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/kitchen_display_system' => [Controllers\KitchenDisplaySystemController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/kitchen_display_system' => [Controllers\KitchenDisplaySystemController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/kitchen_display_system/{id}' => [Controllers\KitchenDisplaySystemController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/kitchen_display_system/{id}' => [Controllers\KitchenDisplaySystemController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/kitchen_display_system/{id}' => [Controllers\KitchenDisplaySystemController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/kitchen_printing' => [Controllers\KitchenPrintingController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/kitchen_printing' => [Controllers\KitchenPrintingController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/kitchen_printing/{id}' => [Controllers\KitchenPrintingController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/kitchen_printing/{id}' => [Controllers\KitchenPrintingController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/kitchen_printing/{id}' => [Controllers\KitchenPrintingController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/cooking_status' => [Controllers\CookingStatusController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/cooking_status' => [Controllers\CookingStatusController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/cooking_status/{id}' => [Controllers\CookingStatusController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/cooking_status/{id}' => [Controllers\CookingStatusController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/cooking_status/{id}' => [Controllers\CookingStatusController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/food_preparation_timers' => [Controllers\FoodPreparationTimersController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/food_preparation_timers' => [Controllers\FoodPreparationTimersController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/food_preparation_timers/{id}' => [Controllers\FoodPreparationTimersController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/food_preparation_timers/{id}' => [Controllers\FoodPreparationTimersController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/food_preparation_timers/{id}' => [Controllers\FoodPreparationTimersController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/recipe_management' => [Controllers\RecipeManagementController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/recipe_management' => [Controllers\RecipeManagementController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/recipe_management/{id}' => [Controllers\RecipeManagementController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/recipe_management/{id}' => [Controllers\RecipeManagementController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/recipe_management/{id}' => [Controllers\RecipeManagementController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/ingredients_tracking' => [Controllers\IngredientsTrackingController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/ingredients_tracking' => [Controllers\IngredientsTrackingController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/ingredients_tracking/{id}' => [Controllers\IngredientsTrackingController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/ingredients_tracking/{id}' => [Controllers\IngredientsTrackingController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/ingredients_tracking/{id}' => [Controllers\IngredientsTrackingController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/waiter_assignment' => [Controllers\WaiterAssignmentController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/waiter_assignment' => [Controllers\WaiterAssignmentController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/waiter_assignment/{id}' => [Controllers\WaiterAssignmentController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/waiter_assignment/{id}' => [Controllers\WaiterAssignmentController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/waiter_assignment/{id}' => [Controllers\WaiterAssignmentController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/waiter_commissions' => [Controllers\WaiterCommissionsController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/waiter_commissions' => [Controllers\WaiterCommissionsController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/waiter_commissions/{id}' => [Controllers\WaiterCommissionsController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/waiter_commissions/{id}' => [Controllers\WaiterCommissionsController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/waiter_commissions/{id}' => [Controllers\WaiterCommissionsController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/order_tracking' => [Controllers\OrderTrackingController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/order_tracking' => [Controllers\OrderTrackingController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/order_tracking/{id}' => [Controllers\OrderTrackingController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/order_tracking/{id}' => [Controllers\OrderTrackingController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/order_tracking/{id}' => [Controllers\OrderTrackingController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/menu_categories' => [Controllers\MenuCategoriesController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/menu_categories' => [Controllers\MenuCategoriesController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/menu_categories/{id}' => [Controllers\MenuCategoriesController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/menu_categories/{id}' => [Controllers\MenuCategoriesController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/menu_categories/{id}' => [Controllers\MenuCategoriesController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/combos' => [Controllers\CombosController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/combos' => [Controllers\CombosController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/combos/{id}' => [Controllers\CombosController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/combos/{id}' => [Controllers\CombosController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/combos/{id}' => [Controllers\CombosController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/meal_customization' => [Controllers\MealCustomizationController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/meal_customization' => [Controllers\MealCustomizationController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/meal_customization/{id}' => [Controllers\MealCustomizationController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/meal_customization/{id}' => [Controllers\MealCustomizationController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/meal_customization/{id}' => [Controllers\MealCustomizationController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/add_ons' => [Controllers\AddOnsController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/add_ons' => [Controllers\AddOnsController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/add_ons/{id}' => [Controllers\AddOnsController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/add_ons/{id}' => [Controllers\AddOnsController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/add_ons/{id}' => [Controllers\AddOnsController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/happy_hour_pricing' => [Controllers\HappyHourPricingController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/happy_hour_pricing' => [Controllers\HappyHourPricingController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/happy_hour_pricing/{id}' => [Controllers\HappyHourPricingController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/happy_hour_pricing/{id}' => [Controllers\HappyHourPricingController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/happy_hour_pricing/{id}' => [Controllers\HappyHourPricingController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/delivery_riders' => [Controllers\DeliveryRidersController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/delivery_riders' => [Controllers\DeliveryRidersController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/delivery_riders/{id}' => [Controllers\DeliveryRidersController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/delivery_riders/{id}' => [Controllers\DeliveryRidersController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/delivery_riders/{id}' => [Controllers\DeliveryRidersController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/delivery_tracking' => [Controllers\DeliveryTrackingController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/delivery_tracking' => [Controllers\DeliveryTrackingController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/delivery_tracking/{id}' => [Controllers\DeliveryTrackingController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/delivery_tracking/{id}' => [Controllers\DeliveryTrackingController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/delivery_tracking/{id}' => [Controllers\DeliveryTrackingController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/online_orders' => [Controllers\OnlineOrdersController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/online_orders' => [Controllers\OnlineOrdersController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/online_orders/{id}' => [Controllers\OnlineOrdersController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/online_orders/{id}' => [Controllers\OnlineOrdersController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/online_orders/{id}' => [Controllers\OnlineOrdersController::class, 'destroy'],
            'GET /api/modules/restaurant_hotels/restaurant/pickup_orders' => [Controllers\PickupOrdersController::class, 'index'],
            'POST /api/modules/restaurant_hotels/restaurant/pickup_orders' => [Controllers\PickupOrdersController::class, 'store'],
            'GET /api/modules/restaurant_hotels/restaurant/pickup_orders/{id}' => [Controllers\PickupOrdersController::class, 'show'],
            'PUT /api/modules/restaurant_hotels/restaurant/pickup_orders/{id}' => [Controllers\PickupOrdersController::class, 'update'],
            'DELETE /api/modules/restaurant_hotels/restaurant/pickup_orders/{id}' => [Controllers\PickupOrdersController::class, 'destroy'],
        ];
    }
}
