<?php

namespace App\Backend\Modules\Core\SalesPos;

class SalesPosModule
{
    public const MODULE_KEY = 'sales_pos';

    public static function features(): array
    {
        return [
            'fast_checkout',
            'barcode_scanning',
            'qr_code_scanning',
            'touch_screen_mode',
            'product_search',
            'product_variants',
            'multiple_payment_methods',
            'split_payments',
            'partial_payments',
            'discounts',
            'coupons',
            'promotions',
            'layaway_sales',
            'quotes',
            'sales_orders',
            'credit_sales',
            'returns',
            'refunds',
            'exchanges',
            'gift_cards',
            'store_credit',
        ];
    }

    public static function routes(): array
    {
        return [
            'GET /api/modules/sales_pos/fast_checkout' => [Controllers\FastCheckoutController::class, 'index'],
            'POST /api/modules/sales_pos/fast_checkout' => [Controllers\FastCheckoutController::class, 'store'],
            'GET /api/modules/sales_pos/fast_checkout/{id}' => [Controllers\FastCheckoutController::class, 'show'],
            'PUT /api/modules/sales_pos/fast_checkout/{id}' => [Controllers\FastCheckoutController::class, 'update'],
            'DELETE /api/modules/sales_pos/fast_checkout/{id}' => [Controllers\FastCheckoutController::class, 'destroy'],
            'GET /api/modules/sales_pos/barcode_scanning' => [Controllers\BarcodeScanningController::class, 'index'],
            'POST /api/modules/sales_pos/barcode_scanning' => [Controllers\BarcodeScanningController::class, 'store'],
            'GET /api/modules/sales_pos/barcode_scanning/{id}' => [Controllers\BarcodeScanningController::class, 'show'],
            'PUT /api/modules/sales_pos/barcode_scanning/{id}' => [Controllers\BarcodeScanningController::class, 'update'],
            'DELETE /api/modules/sales_pos/barcode_scanning/{id}' => [Controllers\BarcodeScanningController::class, 'destroy'],
            'GET /api/modules/sales_pos/qr_code_scanning' => [Controllers\QrCodeScanningController::class, 'index'],
            'POST /api/modules/sales_pos/qr_code_scanning' => [Controllers\QrCodeScanningController::class, 'store'],
            'GET /api/modules/sales_pos/qr_code_scanning/{id}' => [Controllers\QrCodeScanningController::class, 'show'],
            'PUT /api/modules/sales_pos/qr_code_scanning/{id}' => [Controllers\QrCodeScanningController::class, 'update'],
            'DELETE /api/modules/sales_pos/qr_code_scanning/{id}' => [Controllers\QrCodeScanningController::class, 'destroy'],
            'GET /api/modules/sales_pos/touch_screen_mode' => [Controllers\TouchScreenModeController::class, 'index'],
            'POST /api/modules/sales_pos/touch_screen_mode' => [Controllers\TouchScreenModeController::class, 'store'],
            'GET /api/modules/sales_pos/touch_screen_mode/{id}' => [Controllers\TouchScreenModeController::class, 'show'],
            'PUT /api/modules/sales_pos/touch_screen_mode/{id}' => [Controllers\TouchScreenModeController::class, 'update'],
            'DELETE /api/modules/sales_pos/touch_screen_mode/{id}' => [Controllers\TouchScreenModeController::class, 'destroy'],
            'GET /api/modules/sales_pos/product_search' => [Controllers\ProductSearchController::class, 'index'],
            'POST /api/modules/sales_pos/product_search' => [Controllers\ProductSearchController::class, 'store'],
            'GET /api/modules/sales_pos/product_search/{id}' => [Controllers\ProductSearchController::class, 'show'],
            'PUT /api/modules/sales_pos/product_search/{id}' => [Controllers\ProductSearchController::class, 'update'],
            'DELETE /api/modules/sales_pos/product_search/{id}' => [Controllers\ProductSearchController::class, 'destroy'],
            'GET /api/modules/sales_pos/product_variants' => [Controllers\ProductVariantsController::class, 'index'],
            'POST /api/modules/sales_pos/product_variants' => [Controllers\ProductVariantsController::class, 'store'],
            'GET /api/modules/sales_pos/product_variants/{id}' => [Controllers\ProductVariantsController::class, 'show'],
            'PUT /api/modules/sales_pos/product_variants/{id}' => [Controllers\ProductVariantsController::class, 'update'],
            'DELETE /api/modules/sales_pos/product_variants/{id}' => [Controllers\ProductVariantsController::class, 'destroy'],
            'GET /api/modules/sales_pos/multiple_payment_methods' => [Controllers\MultiplePaymentMethodsController::class, 'index'],
            'POST /api/modules/sales_pos/multiple_payment_methods' => [Controllers\MultiplePaymentMethodsController::class, 'store'],
            'GET /api/modules/sales_pos/multiple_payment_methods/{id}' => [Controllers\MultiplePaymentMethodsController::class, 'show'],
            'PUT /api/modules/sales_pos/multiple_payment_methods/{id}' => [Controllers\MultiplePaymentMethodsController::class, 'update'],
            'DELETE /api/modules/sales_pos/multiple_payment_methods/{id}' => [Controllers\MultiplePaymentMethodsController::class, 'destroy'],
            'GET /api/modules/sales_pos/split_payments' => [Controllers\SplitPaymentsController::class, 'index'],
            'POST /api/modules/sales_pos/split_payments' => [Controllers\SplitPaymentsController::class, 'store'],
            'GET /api/modules/sales_pos/split_payments/{id}' => [Controllers\SplitPaymentsController::class, 'show'],
            'PUT /api/modules/sales_pos/split_payments/{id}' => [Controllers\SplitPaymentsController::class, 'update'],
            'DELETE /api/modules/sales_pos/split_payments/{id}' => [Controllers\SplitPaymentsController::class, 'destroy'],
            'GET /api/modules/sales_pos/partial_payments' => [Controllers\PartialPaymentsController::class, 'index'],
            'POST /api/modules/sales_pos/partial_payments' => [Controllers\PartialPaymentsController::class, 'store'],
            'GET /api/modules/sales_pos/partial_payments/{id}' => [Controllers\PartialPaymentsController::class, 'show'],
            'PUT /api/modules/sales_pos/partial_payments/{id}' => [Controllers\PartialPaymentsController::class, 'update'],
            'DELETE /api/modules/sales_pos/partial_payments/{id}' => [Controllers\PartialPaymentsController::class, 'destroy'],
            'GET /api/modules/sales_pos/discounts' => [Controllers\DiscountsController::class, 'index'],
            'POST /api/modules/sales_pos/discounts' => [Controllers\DiscountsController::class, 'store'],
            'GET /api/modules/sales_pos/discounts/{id}' => [Controllers\DiscountsController::class, 'show'],
            'PUT /api/modules/sales_pos/discounts/{id}' => [Controllers\DiscountsController::class, 'update'],
            'DELETE /api/modules/sales_pos/discounts/{id}' => [Controllers\DiscountsController::class, 'destroy'],
            'GET /api/modules/sales_pos/coupons' => [Controllers\CouponsController::class, 'index'],
            'POST /api/modules/sales_pos/coupons' => [Controllers\CouponsController::class, 'store'],
            'GET /api/modules/sales_pos/coupons/{id}' => [Controllers\CouponsController::class, 'show'],
            'PUT /api/modules/sales_pos/coupons/{id}' => [Controllers\CouponsController::class, 'update'],
            'DELETE /api/modules/sales_pos/coupons/{id}' => [Controllers\CouponsController::class, 'destroy'],
            'GET /api/modules/sales_pos/promotions' => [Controllers\PromotionsController::class, 'index'],
            'POST /api/modules/sales_pos/promotions' => [Controllers\PromotionsController::class, 'store'],
            'GET /api/modules/sales_pos/promotions/{id}' => [Controllers\PromotionsController::class, 'show'],
            'PUT /api/modules/sales_pos/promotions/{id}' => [Controllers\PromotionsController::class, 'update'],
            'DELETE /api/modules/sales_pos/promotions/{id}' => [Controllers\PromotionsController::class, 'destroy'],
            'GET /api/modules/sales_pos/layaway_sales' => [Controllers\LayawaySalesController::class, 'index'],
            'POST /api/modules/sales_pos/layaway_sales' => [Controllers\LayawaySalesController::class, 'store'],
            'GET /api/modules/sales_pos/layaway_sales/{id}' => [Controllers\LayawaySalesController::class, 'show'],
            'PUT /api/modules/sales_pos/layaway_sales/{id}' => [Controllers\LayawaySalesController::class, 'update'],
            'DELETE /api/modules/sales_pos/layaway_sales/{id}' => [Controllers\LayawaySalesController::class, 'destroy'],
            'GET /api/modules/sales_pos/quotes' => [Controllers\QuotesController::class, 'index'],
            'POST /api/modules/sales_pos/quotes' => [Controllers\QuotesController::class, 'store'],
            'GET /api/modules/sales_pos/quotes/{id}' => [Controllers\QuotesController::class, 'show'],
            'PUT /api/modules/sales_pos/quotes/{id}' => [Controllers\QuotesController::class, 'update'],
            'DELETE /api/modules/sales_pos/quotes/{id}' => [Controllers\QuotesController::class, 'destroy'],
            'GET /api/modules/sales_pos/sales_orders' => [Controllers\SalesOrdersController::class, 'index'],
            'POST /api/modules/sales_pos/sales_orders' => [Controllers\SalesOrdersController::class, 'store'],
            'GET /api/modules/sales_pos/sales_orders/{id}' => [Controllers\SalesOrdersController::class, 'show'],
            'PUT /api/modules/sales_pos/sales_orders/{id}' => [Controllers\SalesOrdersController::class, 'update'],
            'DELETE /api/modules/sales_pos/sales_orders/{id}' => [Controllers\SalesOrdersController::class, 'destroy'],
            'GET /api/modules/sales_pos/credit_sales' => [Controllers\CreditSalesController::class, 'index'],
            'POST /api/modules/sales_pos/credit_sales' => [Controllers\CreditSalesController::class, 'store'],
            'GET /api/modules/sales_pos/credit_sales/{id}' => [Controllers\CreditSalesController::class, 'show'],
            'PUT /api/modules/sales_pos/credit_sales/{id}' => [Controllers\CreditSalesController::class, 'update'],
            'DELETE /api/modules/sales_pos/credit_sales/{id}' => [Controllers\CreditSalesController::class, 'destroy'],
            'GET /api/modules/sales_pos/returns' => [Controllers\ReturnsController::class, 'index'],
            'POST /api/modules/sales_pos/returns' => [Controllers\ReturnsController::class, 'store'],
            'GET /api/modules/sales_pos/returns/{id}' => [Controllers\ReturnsController::class, 'show'],
            'PUT /api/modules/sales_pos/returns/{id}' => [Controllers\ReturnsController::class, 'update'],
            'DELETE /api/modules/sales_pos/returns/{id}' => [Controllers\ReturnsController::class, 'destroy'],
            'GET /api/modules/sales_pos/refunds' => [Controllers\RefundsController::class, 'index'],
            'POST /api/modules/sales_pos/refunds' => [Controllers\RefundsController::class, 'store'],
            'GET /api/modules/sales_pos/refunds/{id}' => [Controllers\RefundsController::class, 'show'],
            'PUT /api/modules/sales_pos/refunds/{id}' => [Controllers\RefundsController::class, 'update'],
            'DELETE /api/modules/sales_pos/refunds/{id}' => [Controllers\RefundsController::class, 'destroy'],
            'GET /api/modules/sales_pos/exchanges' => [Controllers\ExchangesController::class, 'index'],
            'POST /api/modules/sales_pos/exchanges' => [Controllers\ExchangesController::class, 'store'],
            'GET /api/modules/sales_pos/exchanges/{id}' => [Controllers\ExchangesController::class, 'show'],
            'PUT /api/modules/sales_pos/exchanges/{id}' => [Controllers\ExchangesController::class, 'update'],
            'DELETE /api/modules/sales_pos/exchanges/{id}' => [Controllers\ExchangesController::class, 'destroy'],
            'GET /api/modules/sales_pos/gift_cards' => [Controllers\GiftCardsController::class, 'index'],
            'POST /api/modules/sales_pos/gift_cards' => [Controllers\GiftCardsController::class, 'store'],
            'GET /api/modules/sales_pos/gift_cards/{id}' => [Controllers\GiftCardsController::class, 'show'],
            'PUT /api/modules/sales_pos/gift_cards/{id}' => [Controllers\GiftCardsController::class, 'update'],
            'DELETE /api/modules/sales_pos/gift_cards/{id}' => [Controllers\GiftCardsController::class, 'destroy'],
            'GET /api/modules/sales_pos/store_credit' => [Controllers\StoreCreditController::class, 'index'],
            'POST /api/modules/sales_pos/store_credit' => [Controllers\StoreCreditController::class, 'store'],
            'GET /api/modules/sales_pos/store_credit/{id}' => [Controllers\StoreCreditController::class, 'show'],
            'PUT /api/modules/sales_pos/store_credit/{id}' => [Controllers\StoreCreditController::class, 'update'],
            'DELETE /api/modules/sales_pos/store_credit/{id}' => [Controllers\StoreCreditController::class, 'destroy'],
        ];
    }
}
