<?php

namespace App\Backend\Modules\Core\UserRoles;

class UserRolesModule
{
    public const MODULE_KEY = 'user_roles';

    public static function features(): array
    {
        return [
            'super_admin',
            'business_owner',
            'branch_manager',
            'cashier',
            'salesperson',
            'accountant',
            'inventory_officer',
            'pharmacist',
            'doctor',
            'receptionist',
            'waiter',
            'chef',
            'bartender',
            'barber',
            'stylist',
            'laboratory_technician',
            'security',
            'two_factor_authentication',
            'pin_login',
            'activity_logs',
            'audit_trail',
            'session_management',
            'device_management',
            'ip_restrictions',
            'permission_management',
        ];
    }

    public static function routes(): array
    {
        return [
            'GET /api/modules/user_roles/super_admin' => [Controllers\SuperAdminController::class, 'index'],
            'POST /api/modules/user_roles/super_admin' => [Controllers\SuperAdminController::class, 'store'],
            'GET /api/modules/user_roles/super_admin/{id}' => [Controllers\SuperAdminController::class, 'show'],
            'PUT /api/modules/user_roles/super_admin/{id}' => [Controllers\SuperAdminController::class, 'update'],
            'DELETE /api/modules/user_roles/super_admin/{id}' => [Controllers\SuperAdminController::class, 'destroy'],
            'GET /api/modules/user_roles/business_owner' => [Controllers\BusinessOwnerController::class, 'index'],
            'POST /api/modules/user_roles/business_owner' => [Controllers\BusinessOwnerController::class, 'store'],
            'GET /api/modules/user_roles/business_owner/{id}' => [Controllers\BusinessOwnerController::class, 'show'],
            'PUT /api/modules/user_roles/business_owner/{id}' => [Controllers\BusinessOwnerController::class, 'update'],
            'DELETE /api/modules/user_roles/business_owner/{id}' => [Controllers\BusinessOwnerController::class, 'destroy'],
            'GET /api/modules/user_roles/branch_manager' => [Controllers\BranchManagerController::class, 'index'],
            'POST /api/modules/user_roles/branch_manager' => [Controllers\BranchManagerController::class, 'store'],
            'GET /api/modules/user_roles/branch_manager/{id}' => [Controllers\BranchManagerController::class, 'show'],
            'PUT /api/modules/user_roles/branch_manager/{id}' => [Controllers\BranchManagerController::class, 'update'],
            'DELETE /api/modules/user_roles/branch_manager/{id}' => [Controllers\BranchManagerController::class, 'destroy'],
            'GET /api/modules/user_roles/cashier' => [Controllers\CashierController::class, 'index'],
            'POST /api/modules/user_roles/cashier' => [Controllers\CashierController::class, 'store'],
            'GET /api/modules/user_roles/cashier/{id}' => [Controllers\CashierController::class, 'show'],
            'PUT /api/modules/user_roles/cashier/{id}' => [Controllers\CashierController::class, 'update'],
            'DELETE /api/modules/user_roles/cashier/{id}' => [Controllers\CashierController::class, 'destroy'],
            'GET /api/modules/user_roles/salesperson' => [Controllers\SalespersonController::class, 'index'],
            'POST /api/modules/user_roles/salesperson' => [Controllers\SalespersonController::class, 'store'],
            'GET /api/modules/user_roles/salesperson/{id}' => [Controllers\SalespersonController::class, 'show'],
            'PUT /api/modules/user_roles/salesperson/{id}' => [Controllers\SalespersonController::class, 'update'],
            'DELETE /api/modules/user_roles/salesperson/{id}' => [Controllers\SalespersonController::class, 'destroy'],
            'GET /api/modules/user_roles/accountant' => [Controllers\AccountantController::class, 'index'],
            'POST /api/modules/user_roles/accountant' => [Controllers\AccountantController::class, 'store'],
            'GET /api/modules/user_roles/accountant/{id}' => [Controllers\AccountantController::class, 'show'],
            'PUT /api/modules/user_roles/accountant/{id}' => [Controllers\AccountantController::class, 'update'],
            'DELETE /api/modules/user_roles/accountant/{id}' => [Controllers\AccountantController::class, 'destroy'],
            'GET /api/modules/user_roles/inventory_officer' => [Controllers\InventoryOfficerController::class, 'index'],
            'POST /api/modules/user_roles/inventory_officer' => [Controllers\InventoryOfficerController::class, 'store'],
            'GET /api/modules/user_roles/inventory_officer/{id}' => [Controllers\InventoryOfficerController::class, 'show'],
            'PUT /api/modules/user_roles/inventory_officer/{id}' => [Controllers\InventoryOfficerController::class, 'update'],
            'DELETE /api/modules/user_roles/inventory_officer/{id}' => [Controllers\InventoryOfficerController::class, 'destroy'],
            'GET /api/modules/user_roles/pharmacist' => [Controllers\PharmacistController::class, 'index'],
            'POST /api/modules/user_roles/pharmacist' => [Controllers\PharmacistController::class, 'store'],
            'GET /api/modules/user_roles/pharmacist/{id}' => [Controllers\PharmacistController::class, 'show'],
            'PUT /api/modules/user_roles/pharmacist/{id}' => [Controllers\PharmacistController::class, 'update'],
            'DELETE /api/modules/user_roles/pharmacist/{id}' => [Controllers\PharmacistController::class, 'destroy'],
            'GET /api/modules/user_roles/doctor' => [Controllers\DoctorController::class, 'index'],
            'POST /api/modules/user_roles/doctor' => [Controllers\DoctorController::class, 'store'],
            'GET /api/modules/user_roles/doctor/{id}' => [Controllers\DoctorController::class, 'show'],
            'PUT /api/modules/user_roles/doctor/{id}' => [Controllers\DoctorController::class, 'update'],
            'DELETE /api/modules/user_roles/doctor/{id}' => [Controllers\DoctorController::class, 'destroy'],
            'GET /api/modules/user_roles/receptionist' => [Controllers\ReceptionistController::class, 'index'],
            'POST /api/modules/user_roles/receptionist' => [Controllers\ReceptionistController::class, 'store'],
            'GET /api/modules/user_roles/receptionist/{id}' => [Controllers\ReceptionistController::class, 'show'],
            'PUT /api/modules/user_roles/receptionist/{id}' => [Controllers\ReceptionistController::class, 'update'],
            'DELETE /api/modules/user_roles/receptionist/{id}' => [Controllers\ReceptionistController::class, 'destroy'],
            'GET /api/modules/user_roles/waiter' => [Controllers\WaiterController::class, 'index'],
            'POST /api/modules/user_roles/waiter' => [Controllers\WaiterController::class, 'store'],
            'GET /api/modules/user_roles/waiter/{id}' => [Controllers\WaiterController::class, 'show'],
            'PUT /api/modules/user_roles/waiter/{id}' => [Controllers\WaiterController::class, 'update'],
            'DELETE /api/modules/user_roles/waiter/{id}' => [Controllers\WaiterController::class, 'destroy'],
            'GET /api/modules/user_roles/chef' => [Controllers\ChefController::class, 'index'],
            'POST /api/modules/user_roles/chef' => [Controllers\ChefController::class, 'store'],
            'GET /api/modules/user_roles/chef/{id}' => [Controllers\ChefController::class, 'show'],
            'PUT /api/modules/user_roles/chef/{id}' => [Controllers\ChefController::class, 'update'],
            'DELETE /api/modules/user_roles/chef/{id}' => [Controllers\ChefController::class, 'destroy'],
            'GET /api/modules/user_roles/bartender' => [Controllers\BartenderController::class, 'index'],
            'POST /api/modules/user_roles/bartender' => [Controllers\BartenderController::class, 'store'],
            'GET /api/modules/user_roles/bartender/{id}' => [Controllers\BartenderController::class, 'show'],
            'PUT /api/modules/user_roles/bartender/{id}' => [Controllers\BartenderController::class, 'update'],
            'DELETE /api/modules/user_roles/bartender/{id}' => [Controllers\BartenderController::class, 'destroy'],
            'GET /api/modules/user_roles/barber' => [Controllers\BarberController::class, 'index'],
            'POST /api/modules/user_roles/barber' => [Controllers\BarberController::class, 'store'],
            'GET /api/modules/user_roles/barber/{id}' => [Controllers\BarberController::class, 'show'],
            'PUT /api/modules/user_roles/barber/{id}' => [Controllers\BarberController::class, 'update'],
            'DELETE /api/modules/user_roles/barber/{id}' => [Controllers\BarberController::class, 'destroy'],
            'GET /api/modules/user_roles/stylist' => [Controllers\StylistController::class, 'index'],
            'POST /api/modules/user_roles/stylist' => [Controllers\StylistController::class, 'store'],
            'GET /api/modules/user_roles/stylist/{id}' => [Controllers\StylistController::class, 'show'],
            'PUT /api/modules/user_roles/stylist/{id}' => [Controllers\StylistController::class, 'update'],
            'DELETE /api/modules/user_roles/stylist/{id}' => [Controllers\StylistController::class, 'destroy'],
            'GET /api/modules/user_roles/laboratory_technician' => [Controllers\LaboratoryTechnicianController::class, 'index'],
            'POST /api/modules/user_roles/laboratory_technician' => [Controllers\LaboratoryTechnicianController::class, 'store'],
            'GET /api/modules/user_roles/laboratory_technician/{id}' => [Controllers\LaboratoryTechnicianController::class, 'show'],
            'PUT /api/modules/user_roles/laboratory_technician/{id}' => [Controllers\LaboratoryTechnicianController::class, 'update'],
            'DELETE /api/modules/user_roles/laboratory_technician/{id}' => [Controllers\LaboratoryTechnicianController::class, 'destroy'],
            'GET /api/modules/user_roles/security' => [Controllers\SecurityController::class, 'index'],
            'POST /api/modules/user_roles/security' => [Controllers\SecurityController::class, 'store'],
            'GET /api/modules/user_roles/security/{id}' => [Controllers\SecurityController::class, 'show'],
            'PUT /api/modules/user_roles/security/{id}' => [Controllers\SecurityController::class, 'update'],
            'DELETE /api/modules/user_roles/security/{id}' => [Controllers\SecurityController::class, 'destroy'],
            'GET /api/modules/user_roles/two_factor_authentication' => [Controllers\TwoFactorAuthenticationController::class, 'index'],
            'POST /api/modules/user_roles/two_factor_authentication' => [Controllers\TwoFactorAuthenticationController::class, 'store'],
            'GET /api/modules/user_roles/two_factor_authentication/{id}' => [Controllers\TwoFactorAuthenticationController::class, 'show'],
            'PUT /api/modules/user_roles/two_factor_authentication/{id}' => [Controllers\TwoFactorAuthenticationController::class, 'update'],
            'DELETE /api/modules/user_roles/two_factor_authentication/{id}' => [Controllers\TwoFactorAuthenticationController::class, 'destroy'],
            'GET /api/modules/user_roles/pin_login' => [Controllers\PinLoginController::class, 'index'],
            'POST /api/modules/user_roles/pin_login' => [Controllers\PinLoginController::class, 'store'],
            'GET /api/modules/user_roles/pin_login/{id}' => [Controllers\PinLoginController::class, 'show'],
            'PUT /api/modules/user_roles/pin_login/{id}' => [Controllers\PinLoginController::class, 'update'],
            'DELETE /api/modules/user_roles/pin_login/{id}' => [Controllers\PinLoginController::class, 'destroy'],
            'GET /api/modules/user_roles/activity_logs' => [Controllers\ActivityLogsController::class, 'index'],
            'POST /api/modules/user_roles/activity_logs' => [Controllers\ActivityLogsController::class, 'store'],
            'GET /api/modules/user_roles/activity_logs/{id}' => [Controllers\ActivityLogsController::class, 'show'],
            'PUT /api/modules/user_roles/activity_logs/{id}' => [Controllers\ActivityLogsController::class, 'update'],
            'DELETE /api/modules/user_roles/activity_logs/{id}' => [Controllers\ActivityLogsController::class, 'destroy'],
            'GET /api/modules/user_roles/audit_trail' => [Controllers\AuditTrailController::class, 'index'],
            'POST /api/modules/user_roles/audit_trail' => [Controllers\AuditTrailController::class, 'store'],
            'GET /api/modules/user_roles/audit_trail/{id}' => [Controllers\AuditTrailController::class, 'show'],
            'PUT /api/modules/user_roles/audit_trail/{id}' => [Controllers\AuditTrailController::class, 'update'],
            'DELETE /api/modules/user_roles/audit_trail/{id}' => [Controllers\AuditTrailController::class, 'destroy'],
            'GET /api/modules/user_roles/session_management' => [Controllers\SessionManagementController::class, 'index'],
            'POST /api/modules/user_roles/session_management' => [Controllers\SessionManagementController::class, 'store'],
            'GET /api/modules/user_roles/session_management/{id}' => [Controllers\SessionManagementController::class, 'show'],
            'PUT /api/modules/user_roles/session_management/{id}' => [Controllers\SessionManagementController::class, 'update'],
            'DELETE /api/modules/user_roles/session_management/{id}' => [Controllers\SessionManagementController::class, 'destroy'],
            'GET /api/modules/user_roles/device_management' => [Controllers\DeviceManagementController::class, 'index'],
            'POST /api/modules/user_roles/device_management' => [Controllers\DeviceManagementController::class, 'store'],
            'GET /api/modules/user_roles/device_management/{id}' => [Controllers\DeviceManagementController::class, 'show'],
            'PUT /api/modules/user_roles/device_management/{id}' => [Controllers\DeviceManagementController::class, 'update'],
            'DELETE /api/modules/user_roles/device_management/{id}' => [Controllers\DeviceManagementController::class, 'destroy'],
            'GET /api/modules/user_roles/ip_restrictions' => [Controllers\IpRestrictionsController::class, 'index'],
            'POST /api/modules/user_roles/ip_restrictions' => [Controllers\IpRestrictionsController::class, 'store'],
            'GET /api/modules/user_roles/ip_restrictions/{id}' => [Controllers\IpRestrictionsController::class, 'show'],
            'PUT /api/modules/user_roles/ip_restrictions/{id}' => [Controllers\IpRestrictionsController::class, 'update'],
            'DELETE /api/modules/user_roles/ip_restrictions/{id}' => [Controllers\IpRestrictionsController::class, 'destroy'],
            'GET /api/modules/user_roles/permission_management' => [Controllers\PermissionManagementController::class, 'index'],
            'POST /api/modules/user_roles/permission_management' => [Controllers\PermissionManagementController::class, 'store'],
            'GET /api/modules/user_roles/permission_management/{id}' => [Controllers\PermissionManagementController::class, 'show'],
            'PUT /api/modules/user_roles/permission_management/{id}' => [Controllers\PermissionManagementController::class, 'update'],
            'DELETE /api/modules/user_roles/permission_management/{id}' => [Controllers\PermissionManagementController::class, 'destroy'],
        ];
    }
}
