<?php

namespace App\Backend\Modules\Registry;

class CoreModules
{
    public static function all(): array
    {
        return [
            'business_management' => [
                'name' => 'Business Management',
                'description' => 'Company profile, branding, tax, currency, and operating hours.',
                'category' => 'core',
                'icon' => 'building',
                'features' => [
                    'business_registration',
                    'company_profile',
                    'business_logo_branding',
                    'multiple_businesses',
                    'tax_configuration',
                    'currency_settings',
                    'timezone_settings',
                    'operating_hours',
                ],
            ],
            'dashboard' => [
                'name' => 'Dashboard',
                'description' => 'Sales analytics, profit analysis, and performance insights.',
                'category' => 'core',
                'icon' => 'chart-bar',
                'features' => [
                    'daily_sales',
                    'weekly_sales',
                    'monthly_sales',
                    'annual_reports',
                    'profit_analysis',
                    'expenses',
                    'cash_flow',
                    'top_selling_products',
                    'least_selling_products',
                    'best_customers',
                    'stock_alerts',
                    'employee_performance',
                    'branch_comparison',
                    'graphs_analytics',
                ],
            ],
            'sales_pos' => [
                'name' => 'Sales (POS)',
                'description' => 'Fast checkout, payments, discounts, and returns.',
                'category' => 'core',
                'icon' => 'cash-register',
                'features' => [
                    'fast_checkout',
                    'barcode_scanning',
                    'qr_code_scanning',
                    'touch_screen_mode',
                    'product_search',
                    'product_variants',
                    'multiple_payment_methods',
                    'split_payments',
                    'partial_payments',
                    'discounts',
                    'coupons',
                    'promotions',
                    'layaway_sales',
                    'quotes',
                    'sales_orders',
                    'credit_sales',
                    'returns',
                    'refunds',
                    'exchanges',
                    'gift_cards',
                    'store_credit',
                ],
            ],
            'invoicing' => [
                'name' => 'Invoicing',
                'description' => 'Professional invoices, receipts, and tax documents.',
                'category' => 'core',
                'icon' => 'file-invoice',
                'features' => [
                    'professional_invoices',
                    'email_invoices',
                    'whatsapp_invoices',
                    'sms_invoices',
                    'pdf_invoices',
                    'recurring_invoices',
                    'proforma_invoices',
                    'tax_invoices',
                    'invoice_templates',
                    'invoice_numbering',
                    'thermal_printing',
                    'a4_printing',
                    'email_receipts',
                    'whatsapp_receipts',
                    'qr_verification',
                    'custom_branding',
                ],
            ],
            'inventory' => [
                'name' => 'Inventory Management',
                'description' => 'Products, warehouses, stock transfers, and valuation.',
                'category' => 'core',
                'icon' => 'boxes',
                'features' => [
                    'unlimited_products',
                    'categories',
                    'brands',
                    'units',
                    'product_images',
                    'barcode_generation',
                    'batch_numbers',
                    'expiry_dates',
                    'serial_numbers',
                    'stock_transfers',
                    'stock_adjustments',
                    'reorder_levels',
                    'purchase_orders',
                    'supplier_orders',
                    'warehouse_management',
                    'multiple_warehouses',
                    'inventory_valuation',
                    'inventory_history',
                    'damaged_stock',
                    'lost_stock',
                    'cycle_counts',
                ],
            ],
            'purchases' => [
                'name' => 'Purchases',
                'description' => 'Supplier orders, goods received, and payment schedules.',
                'category' => 'core',
                'icon' => 'truck',
                'features' => [
                    'suppliers',
                    'purchase_orders',
                    'goods_received',
                    'supplier_invoices',
                    'supplier_returns',
                    'outstanding_balances',
                    'payment_schedules',
                ],
            ],
            'customers' => [
                'name' => 'Customer Management',
                'description' => 'Customer profiles, loyalty, credit limits, and statements.',
                'category' => 'core',
                'icon' => 'users',
                'features' => [
                    'customer_profiles',
                    'loyalty_points',
                    'memberships',
                    'customer_groups',
                    'credit_limits',
                    'customer_statements',
                    'purchase_history',
                    'birthday_reminders',
                ],
            ],
            'suppliers' => [
                'name' => 'Supplier Management',
                'description' => 'Supplier directory, payments, and outstanding balances.',
                'category' => 'core',
                'icon' => 'handshake',
                'features' => [
                    'supplier_directory',
                    'purchase_history',
                    'payments',
                    'outstanding_balances',
                    'contact_management',
                ],
            ],
            'financials' => [
                'name' => 'Financials',
                'description' => 'Expenses, income, P&L, cashbook, and tax reports.',
                'category' => 'core',
                'icon' => 'coins',
                'features' => [
                    'expenses',
                    'income',
                    'profit_loss',
                    'cashbook',
                    'bank_accounts',
                    'petty_cash',
                    'tax_reports',
                    'vat_reports',
                    'daily_reconciliation',
                ],
            ],
            'employees' => [
                'name' => 'Employee Management',
                'description' => 'Attendance, commissions, payroll, and shift management.',
                'category' => 'core',
                'icon' => 'id-badge',
                'features' => [
                    'employees',
                    'attendance',
                    'commissions',
                    'payroll_integration',
                    'performance_tracking',
                    'sales_targets',
                    'shift_management',
                ],
            ],
            'user_roles' => [
                'name' => 'User Roles & Security',
                'description' => 'Role-based access, 2FA, audit trails, and device management.',
                'category' => 'core',
                'icon' => 'shield',
                'features' => [
                    'super_admin',
                    'business_owner',
                    'branch_manager',
                    'cashier',
                    'salesperson',
                    'accountant',
                    'inventory_officer',
                    'pharmacist',
                    'doctor',
                    'receptionist',
                    'waiter',
                    'chef',
                    'bartender',
                    'barber',
                    'stylist',
                    'laboratory_technician',
                    'security',
                    'two_factor_authentication',
                    'pin_login',
                    'activity_logs',
                    'audit_trail',
                    'session_management',
                    'device_management',
                    'ip_restrictions',
                    'permission_management',
                ],
            ],
            'multi_branch' => [
                'name' => 'Multi-Branch',
                'description' => 'Unlimited branches, transfers, and branch-level reporting.',
                'category' => 'core',
                'icon' => 'sitemap',
                'features' => [
                    'unlimited_branches',
                    'branch_inventory',
                    'branch_transfers',
                    'branch_reports',
                    'branch_managers',
                    'branch_expenses',
                    'central_warehouse',
                ],
            ],
            'reports' => [
                'name' => 'Reports',
                'description' => 'Comprehensive reporting across all business areas.',
                'category' => 'core',
                'icon' => 'chart-pie',
                'features' => [
                    'sales_reports',
                    'inventory_reports',
                    'customer_reports',
                    'supplier_reports',
                    'financial_reports',
                    'employee_reports',
                    'branch_reports',
                    'tax_reports',
                    'product_movement',
                    'commission_reports',
                ],
            ],
        ];
    }
}
