<?php

namespace App\Backend\Modules\Core\Invoicing;

class InvoicingModule
{
    public const MODULE_KEY = 'invoicing';

    public static function features(): array
    {
        return [
            'professional_invoices',
            'email_invoices',
            'whatsapp_invoices',
            'sms_invoices',
            'pdf_invoices',
            'recurring_invoices',
            'proforma_invoices',
            'tax_invoices',
            'invoice_templates',
            'invoice_numbering',
            'thermal_printing',
            'a4_printing',
            'email_receipts',
            'whatsapp_receipts',
            'qr_verification',
            'custom_branding',
        ];
    }

    public static function routes(): array
    {
        return [
            'GET /api/modules/invoicing/professional_invoices' => [Controllers\ProfessionalInvoicesController::class, 'index'],
            'POST /api/modules/invoicing/professional_invoices' => [Controllers\ProfessionalInvoicesController::class, 'store'],
            'GET /api/modules/invoicing/professional_invoices/{id}' => [Controllers\ProfessionalInvoicesController::class, 'show'],
            'PUT /api/modules/invoicing/professional_invoices/{id}' => [Controllers\ProfessionalInvoicesController::class, 'update'],
            'DELETE /api/modules/invoicing/professional_invoices/{id}' => [Controllers\ProfessionalInvoicesController::class, 'destroy'],
            'GET /api/modules/invoicing/email_invoices' => [Controllers\EmailInvoicesController::class, 'index'],
            'POST /api/modules/invoicing/email_invoices' => [Controllers\EmailInvoicesController::class, 'store'],
            'GET /api/modules/invoicing/email_invoices/{id}' => [Controllers\EmailInvoicesController::class, 'show'],
            'PUT /api/modules/invoicing/email_invoices/{id}' => [Controllers\EmailInvoicesController::class, 'update'],
            'DELETE /api/modules/invoicing/email_invoices/{id}' => [Controllers\EmailInvoicesController::class, 'destroy'],
            'GET /api/modules/invoicing/whatsapp_invoices' => [Controllers\WhatsappInvoicesController::class, 'index'],
            'POST /api/modules/invoicing/whatsapp_invoices' => [Controllers\WhatsappInvoicesController::class, 'store'],
            'GET /api/modules/invoicing/whatsapp_invoices/{id}' => [Controllers\WhatsappInvoicesController::class, 'show'],
            'PUT /api/modules/invoicing/whatsapp_invoices/{id}' => [Controllers\WhatsappInvoicesController::class, 'update'],
            'DELETE /api/modules/invoicing/whatsapp_invoices/{id}' => [Controllers\WhatsappInvoicesController::class, 'destroy'],
            'GET /api/modules/invoicing/sms_invoices' => [Controllers\SmsInvoicesController::class, 'index'],
            'POST /api/modules/invoicing/sms_invoices' => [Controllers\SmsInvoicesController::class, 'store'],
            'GET /api/modules/invoicing/sms_invoices/{id}' => [Controllers\SmsInvoicesController::class, 'show'],
            'PUT /api/modules/invoicing/sms_invoices/{id}' => [Controllers\SmsInvoicesController::class, 'update'],
            'DELETE /api/modules/invoicing/sms_invoices/{id}' => [Controllers\SmsInvoicesController::class, 'destroy'],
            'GET /api/modules/invoicing/pdf_invoices' => [Controllers\PdfInvoicesController::class, 'index'],
            'POST /api/modules/invoicing/pdf_invoices' => [Controllers\PdfInvoicesController::class, 'store'],
            'GET /api/modules/invoicing/pdf_invoices/{id}' => [Controllers\PdfInvoicesController::class, 'show'],
            'PUT /api/modules/invoicing/pdf_invoices/{id}' => [Controllers\PdfInvoicesController::class, 'update'],
            'DELETE /api/modules/invoicing/pdf_invoices/{id}' => [Controllers\PdfInvoicesController::class, 'destroy'],
            'GET /api/modules/invoicing/recurring_invoices' => [Controllers\RecurringInvoicesController::class, 'index'],
            'POST /api/modules/invoicing/recurring_invoices' => [Controllers\RecurringInvoicesController::class, 'store'],
            'GET /api/modules/invoicing/recurring_invoices/{id}' => [Controllers\RecurringInvoicesController::class, 'show'],
            'PUT /api/modules/invoicing/recurring_invoices/{id}' => [Controllers\RecurringInvoicesController::class, 'update'],
            'DELETE /api/modules/invoicing/recurring_invoices/{id}' => [Controllers\RecurringInvoicesController::class, 'destroy'],
            'GET /api/modules/invoicing/proforma_invoices' => [Controllers\ProformaInvoicesController::class, 'index'],
            'POST /api/modules/invoicing/proforma_invoices' => [Controllers\ProformaInvoicesController::class, 'store'],
            'GET /api/modules/invoicing/proforma_invoices/{id}' => [Controllers\ProformaInvoicesController::class, 'show'],
            'PUT /api/modules/invoicing/proforma_invoices/{id}' => [Controllers\ProformaInvoicesController::class, 'update'],
            'DELETE /api/modules/invoicing/proforma_invoices/{id}' => [Controllers\ProformaInvoicesController::class, 'destroy'],
            'GET /api/modules/invoicing/tax_invoices' => [Controllers\TaxInvoicesController::class, 'index'],
            'POST /api/modules/invoicing/tax_invoices' => [Controllers\TaxInvoicesController::class, 'store'],
            'GET /api/modules/invoicing/tax_invoices/{id}' => [Controllers\TaxInvoicesController::class, 'show'],
            'PUT /api/modules/invoicing/tax_invoices/{id}' => [Controllers\TaxInvoicesController::class, 'update'],
            'DELETE /api/modules/invoicing/tax_invoices/{id}' => [Controllers\TaxInvoicesController::class, 'destroy'],
            'GET /api/modules/invoicing/invoice_templates' => [Controllers\InvoiceTemplatesController::class, 'index'],
            'POST /api/modules/invoicing/invoice_templates' => [Controllers\InvoiceTemplatesController::class, 'store'],
            'GET /api/modules/invoicing/invoice_templates/{id}' => [Controllers\InvoiceTemplatesController::class, 'show'],
            'PUT /api/modules/invoicing/invoice_templates/{id}' => [Controllers\InvoiceTemplatesController::class, 'update'],
            'DELETE /api/modules/invoicing/invoice_templates/{id}' => [Controllers\InvoiceTemplatesController::class, 'destroy'],
            'GET /api/modules/invoicing/invoice_numbering' => [Controllers\InvoiceNumberingController::class, 'index'],
            'POST /api/modules/invoicing/invoice_numbering' => [Controllers\InvoiceNumberingController::class, 'store'],
            'GET /api/modules/invoicing/invoice_numbering/{id}' => [Controllers\InvoiceNumberingController::class, 'show'],
            'PUT /api/modules/invoicing/invoice_numbering/{id}' => [Controllers\InvoiceNumberingController::class, 'update'],
            'DELETE /api/modules/invoicing/invoice_numbering/{id}' => [Controllers\InvoiceNumberingController::class, 'destroy'],
            'GET /api/modules/invoicing/thermal_printing' => [Controllers\ThermalPrintingController::class, 'index'],
            'POST /api/modules/invoicing/thermal_printing' => [Controllers\ThermalPrintingController::class, 'store'],
            'GET /api/modules/invoicing/thermal_printing/{id}' => [Controllers\ThermalPrintingController::class, 'show'],
            'PUT /api/modules/invoicing/thermal_printing/{id}' => [Controllers\ThermalPrintingController::class, 'update'],
            'DELETE /api/modules/invoicing/thermal_printing/{id}' => [Controllers\ThermalPrintingController::class, 'destroy'],
            'GET /api/modules/invoicing/a4_printing' => [Controllers\A4PrintingController::class, 'index'],
            'POST /api/modules/invoicing/a4_printing' => [Controllers\A4PrintingController::class, 'store'],
            'GET /api/modules/invoicing/a4_printing/{id}' => [Controllers\A4PrintingController::class, 'show'],
            'PUT /api/modules/invoicing/a4_printing/{id}' => [Controllers\A4PrintingController::class, 'update'],
            'DELETE /api/modules/invoicing/a4_printing/{id}' => [Controllers\A4PrintingController::class, 'destroy'],
            'GET /api/modules/invoicing/email_receipts' => [Controllers\EmailReceiptsController::class, 'index'],
            'POST /api/modules/invoicing/email_receipts' => [Controllers\EmailReceiptsController::class, 'store'],
            'GET /api/modules/invoicing/email_receipts/{id}' => [Controllers\EmailReceiptsController::class, 'show'],
            'PUT /api/modules/invoicing/email_receipts/{id}' => [Controllers\EmailReceiptsController::class, 'update'],
            'DELETE /api/modules/invoicing/email_receipts/{id}' => [Controllers\EmailReceiptsController::class, 'destroy'],
            'GET /api/modules/invoicing/whatsapp_receipts' => [Controllers\WhatsappReceiptsController::class, 'index'],
            'POST /api/modules/invoicing/whatsapp_receipts' => [Controllers\WhatsappReceiptsController::class, 'store'],
            'GET /api/modules/invoicing/whatsapp_receipts/{id}' => [Controllers\WhatsappReceiptsController::class, 'show'],
            'PUT /api/modules/invoicing/whatsapp_receipts/{id}' => [Controllers\WhatsappReceiptsController::class, 'update'],
            'DELETE /api/modules/invoicing/whatsapp_receipts/{id}' => [Controllers\WhatsappReceiptsController::class, 'destroy'],
            'GET /api/modules/invoicing/qr_verification' => [Controllers\QrVerificationController::class, 'index'],
            'POST /api/modules/invoicing/qr_verification' => [Controllers\QrVerificationController::class, 'store'],
            'GET /api/modules/invoicing/qr_verification/{id}' => [Controllers\QrVerificationController::class, 'show'],
            'PUT /api/modules/invoicing/qr_verification/{id}' => [Controllers\QrVerificationController::class, 'update'],
            'DELETE /api/modules/invoicing/qr_verification/{id}' => [Controllers\QrVerificationController::class, 'destroy'],
            'GET /api/modules/invoicing/custom_branding' => [Controllers\CustomBrandingController::class, 'index'],
            'POST /api/modules/invoicing/custom_branding' => [Controllers\CustomBrandingController::class, 'store'],
            'GET /api/modules/invoicing/custom_branding/{id}' => [Controllers\CustomBrandingController::class, 'show'],
            'PUT /api/modules/invoicing/custom_branding/{id}' => [Controllers\CustomBrandingController::class, 'update'],
            'DELETE /api/modules/invoicing/custom_branding/{id}' => [Controllers\CustomBrandingController::class, 'destroy'],
        ];
    }
}
